'''
this driver will be much simpler than the JYLmaxRcutJointConvTestDriver

In this kind of test, abacus calculation will run in serial from the 
orbital with the lowest kinetic energy cutoff to the highest. If not the
first, the charge density yielded by the previous calculation will be
used as the initial guess of the charge density.
'''

import os
import re
import json
import uuid

# for logging
import time
import logging

# for unittest
import unittest

# because we can only use command line mode on Bohrium, so we need to use argparse
import argparse

# because not sure if the remote has numpy, so use math instead
from math import sin, cos, sqrt, acos, degrees, radians

def _convert_to_int_if_possible(s, thr = 1e-6):
    '''
    convert a float number to int if possible
    '''
    if abs(s - round(s)) < thr:
        return int(round(s))
    return s

def _parse_orb_comp(orb):
    '''
    parse the orb components information in pattern like '21s20p20d19f19g18h'
    '''
    m = re.match(r'((\d+)([spdfghiklm]))+', orb)
    if not m:
        raise ValueError(f'Invalid orb component: {orb}')
    spectrum = 'spdfghiklm'
    lmax = 0
    for s in spectrum[::-1]:
        if s in orb:
            lmax = spectrum.index(s) + 1
            break
    temp = dict([(m.group(2), int(m.group(1))) for m in re.finditer(r'(\d+)([spdfghiklm])', orb)])
    return [temp.get(spectrum[l], 0) for l in range(lmax)]

def _parse_forb(fn):
    '''
    parse the information of an ABACUS orbital file by its name
    '''
    
    fn = os.path.basename(fn) if '/' in fn else fn
    # abacus orbital files' names in format N_gga_7au_100Ry_21s20p20d19f19g18h.orb
    pat = r'^([A-Z][a-z]?)_gga_(\d+)au_(\d+(\.\d+)?)Ry_(\w+)\.orb$'
    m = re.match(pat, fn)
    if not m:
        raise ValueError(f'Invalid orbital file name: {fn}')
    elem, rcut, ecut, _, orbs = m.groups()
    return dict([('elem', elem), 
                 ('rcut', _convert_to_int_if_possible(float(rcut))), 
                 ('ecut', _convert_to_int_if_possible(float(ecut))), 
                 ('nzeta', _parse_orb_comp(orbs))])

def _find_all_orbs(folder):
    '''
    scan all orbitals in present folder, and store the information in a dictionary 
    '''
    logging.info(f'Start to find all orbitals in {folder}...')
    orbs = {}
    for fn in os.listdir(folder):
        if fn.endswith('.orb'):
            rcut = _parse_forb(fn)['rcut']
            lmax = len(_parse_forb(fn)['nzeta']) - 1
            ecut = _parse_forb(fn)['ecut']
            if ecut in orbs:
                errmsg = f'Found two orbitals with the same ecut {ecut}Ry.'
                logging.error(errmsg)
                raise ValueError(errmsg)
            orbs[ecut] = os.path.join(folder, fn)
            logging.info(f'Found orbital file {fn} with ecut {ecut}Ry, rcut {rcut}au, lmax {lmax}.')
    logging.info(f'Summary: found {len(orbs)} orbitals in {folder}.')

    return orbs

def _write_dft_param_set(outdir, dft_param_set):
    '''
    write the ABACUS INPUT file into the outdir
    '''
    if not os.path.exists(outdir):
        os.makedirs(outdir, exist_ok = True)
    fn = os.path.join(outdir, 'INPUT')
    with open(fn, 'w') as f:
        f.write('# this file is automatically generated by the LmaxConvergenceTestDriver\n')
        f.write('INPUT_PARAMETERS\n')
        for k, v in dft_param_set.items():
            f.write(f'{k:<15} {v}\n')
    return fn

def _read_abacus_input(fn):
    '''
    read the abacus input and return a dict
    '''
    with open(fn) as f:
        lines = [l.strip().split('#')[0] for l in f.readlines() if not l.startswith('#')
                 and not l.startswith('INPUT_PARAMETERS')]
    lines = [l for l in lines if l]
    return dict([(l.split()[0], ' '.join(l.split()[1:])) for l in lines])

def _unit_convert(value, from_unit, to_unit):
    '''convert unit'''
    to_unit, from_unit = map(str.lower, [to_unit, from_unit])
    factor = {'bohr': 1, 'angstrom': 0.52917721067}
    return value * factor[to_unit] / factor[from_unit]

def _build_monomer_in_cell(elem, celldm, unit = 'bohr'):
    '''
    build a dict storing cell information
    '''
    celldm = _unit_convert(celldm, 'angstrom', unit)
    return {'a': celldm, 'b': celldm, 'c': celldm, 'alpha': 90, 'beta': 90, 'gamma': 90, 
            'coords': [[0, 0, 0]],
            'labels': [elem], 'kinds': [elem], 'labels_kinds_map': [0]}

def _build_atomspec(elem, fpsp, forb):
    '''
    build a dict storing atom species information
    '''
    return {'symbol': elem, 'pp': fpsp, 'nao': forb}

def _abc_angles_to_vec(a, b, c, alpha, beta, gamma):
    '''
    convert the a, b, c, alpha, beta, gamma to lattice vectors
    '''
    alpha, beta, gamma = [radians(x) for x in (alpha, beta, gamma)]
    na, nb, nc = a, b, c
    a = [na, 0, 0]
    b = [nb * cos(gamma), nb * sin(gamma), 0]
    c1 = nc * cos(beta)
    c2 = (nb * nc * cos(alpha) - b[0] * c1) / b[1]
    c3 = sqrt(nc**2 - c1**2 - c2**2)
    c = [c1, c2, c3]
    return a, b, c

def _vec_to_abc_angles(a, b, c):
    '''
    convert the lattice vectors to a, b, c, alpha, beta, gamma
    '''
    na = sqrt(a[0]**2 + a[1]**2 + a[2]**2)
    nb = sqrt(b[0]**2 + b[1]**2 + b[2]**2)
    nc = sqrt(c[0]**2 + c[1]**2 + c[2]**2)
    alpha = degrees(acos((b[0]*c[0] + b[1]*c[1] + b[2]*c[2]) / (nb * nc)))
    beta = degrees(acos((a[0]*c[0] + a[1]*c[1] + a[2]*c[2]) / (na * nc)))
    gamma = degrees(acos((a[0]*b[0] + a[1]*b[1] + a[2]*b[2]) / (na * nb)))
    return na, nb, nc, alpha, beta, gamma

def _write_abacus_stru(outdir, cell, atom_species):
    '''
    write an ABACUS STRU file into outdir, with the cell dict and atom_species list of dict
    '''
    out =  'ATOMIC_SPECIES\n'
    for a in atom_species:
        out += f'{a["symbol"]} {a.get("mass", 1.000)} {os.path.basename(a["pp"])}\n'
    
    if all([a.get('nao') for a in atom_species]):
        out += '\nNUMERICAL_ORBITAL\n'
        for a in atom_species:
            out += f'{os.path.basename(a["nao"])}\n'

    out += '\nLATTICE_CONSTANT\n1.889726877\n\nLATTICE_VECTORS\n'
    for v in _abc_angles_to_vec(*[cell[k] for k in ['a', 'b', 'c', 'alpha', 'beta', 'gamma']]):
        out += f'{" ".join([f"{x:.10f}" for x in v])}\n'
    
    out += '\nATOMIC_POSITIONS\nCartesian_angstrom_center_xyz\n'
    temp = ''
    for ia, a in enumerate(cell['labels']):
        elem = cell['kinds'][cell['labels_kinds_map'][ia]]
        if temp != elem:
            nat = cell['labels'].count(a)
            out += f'{elem}\n0.00\n{nat}\n'
            temp = elem
        out += f'{" ".join([f"{x:.10f}" for x in cell["coords"][ia]])}\n'
    out += '\n'
    fn = os.path.join(outdir, 'STRU')
    os.makedirs(outdir, exist_ok = True)
    with open(fn, 'w') as f:
        f.write(out)
    return fn

def _write_apns_desc(outdir, dft_param_set, atom_species, cell):
    '''
    write a APNS (ABACUS Pseudopotential Nao Square) job description file (in json)
    '''
    atom_species = [atom_species] if isinstance(atom_species, dict) else atom_species
    symbol = atom_species[0]['symbol']
    desc = {'DFTParamSet': dft_param_set,
            'AtomSpecies': atom_species,
            'Cell': cell,
            'CellGenerator': {'identifier': 'molecule', 'config': f'{symbol}_monomer'}}
    fn = os.path.join(outdir, f'description.json')
    os.makedirs(outdir, exist_ok = True)
    with open(fn, 'w') as f:
        json.dump(desc, f, indent = 4)
    return fn

def _define_outdir(elem, ecutjy, use_uuid = False):
    '''
    define the output directory
    '''
    if use_uuid:
        return str(uuid.uuid4())
    return f'{elem}_{ecutjy}Ry'

def _skip_test(folder):
    '''
    check if the test is already done
    '''
    if not os.path.exists(folder):
        return False
    temp = _read_abacus_input(os.path.join(folder, 'INPUT'))
    suffix, nspin = [temp.get(k, 'ABACUS') for k in ['suffix', 'nspin']]
    nspin = int(nspin)

    outdir = os.path.join(folder, f'OUT.{suffix}')
    if temp.get('scf_nmax', 100) == '1':
        return os.path.exists(os.path.join(outdir, 'istate.info'))
    
    frhog = os.path.join(outdir, f'{suffix}-CHARGE-DENSITY.restart')
    frhor = [os.path.join(outdir, f'SPIN{i}_CHG.cube') for i in range(1, nspin + 1)]
    return os.path.exists(frhog) or all([os.path.exists(f) for f in frhor])

def _init_test(elem, fpsp, forb, ecutjy, celldm, dft_param_set = None, use_uuid = False):
    '''
    initialize a lmax convergence test job with given parameters

    Returns
    -------
    outdir : str
        the output directory
    run : bool
        if True, the job is not skipped
    '''
    default_param_set = {'nspin': 1, 
                         'calculation': 'scf', 
                         'ecutwfc': 100,
                         'nbands': 69,
                         'symmetry': 0,
                         'gamma_only': 1,
                         'basis_type': 'lcao', 
                         'ks_solver': 'genelpa',
                         'smearing_method': 'gauss',
                         'smearing_sigma': 0.015,
                         'mixing_type': 'broyden',
                         'mixing_beta': 0.4,
                         'mixing_ndim': 12,
                         'out_chg': -1, 
                         'init_chg': 'auto',
                         'scf_thr': 1e-2, # a relatively large value, means SCF convergence not relies on it
                         'scf_ene_thr': 1e-8} # in eV, 1 mkcal/mol/atom = 2.15e-05 eV
    dft_param_set = {} if dft_param_set is None else dft_param_set
    dft_param_set = default_param_set | dft_param_set

    cell = _build_monomer_in_cell(elem, celldm, 'angstrom')
    atom_species = _build_atomspec(elem, fpsp, forb)

    orb = _parse_forb(forb) if forb is not None else None
    dft_param_set.update({'pseudo_dir': os.path.dirname(fpsp), 
                          'orbital_dir': os.path.dirname(forb) if forb is not None else None})
    conditional = {'ecutjy': ecutjy, 
                   'use_uuid': use_uuid}
    outdir = _define_outdir(**(conditional|{'elem': elem}))
    if _skip_test(outdir):
        logging.info(f'Test {outdir} is skipped because it is already done.')
        return outdir, False
    _write_abacus_stru(outdir, cell, [atom_species])
    _write_apns_desc(outdir, dft_param_set, atom_species, cell)
    _write_dft_param_set(outdir, dft_param_set)
    return outdir, True

def _init_test_with_charge(folder, forb, ecutjy, use_rhog = False, by_copy = False, dft_param_update = None):
    '''
    once a job is finished, we use the charge density as the initial guess of charge
    to do the next job. The l and rcut parameters will be updated.

    Parameters
    ----------
    folder : str
        the folder containing the previous job
    forb : str
        the new orbital file name
    use_rhog : bool
        if True, use the charge density file stored in Gspace, otherwise use the one
        in realspace. For highly heterogenous system, the realspace one is recommended.
    by_copy : bool
        if True, copy the charge density file, otherwise move it.
    dft_param_update : dict
        the updated DFT parameters
    
    Returns
    -------
    jobdir : str
        the output directory
    run : bool
        if True, the job is not skipped
    '''
    # load the description of the previous job
    desc = os.path.join(folder, 'description.json')
    with open(desc) as f:
        desc = json.load(f)

    # refreshing the dft_param_set
    dft_param_set = desc['DFTParamSet'].copy()
    dft_param_set['init_chg'] = 'file'
    dft_param_set['out_chg'] = 1 if not use_rhog else 0
    dft_param_set.update(dft_param_update or {})
    # we change it to file, so that ABACUS will throw if there is no charge file
    
    atom_species = desc['AtomSpecies'][0]
    elem, fpsp, _ = atom_species['symbol'], atom_species['pp'], atom_species['nao']
    
    cell = desc['Cell']
    celldm = cell['a']

    suffix = _read_abacus_input(os.path.join(folder, 'INPUT')).get('suffix', 'ABACUS')
    outdir = os.path.join(folder, f'OUT.{suffix}')

    jobdir, run = _init_test(elem, fpsp, forb, ecutjy, celldm, dft_param_set)
    if not run: # skip the job if it is already done
        return jobdir, False
    suffix_new = dft_param_set.get('suffix', 'ABACUS')
    outdir_new = os.path.join(jobdir, f'OUT.{suffix_new}')
    os.makedirs(outdir_new, exist_ok = True)

    frhog = os.path.join(outdir, f'{suffix}-CHARGE-DENSITY.restart')
    op = 'cp' if by_copy else 'mv'
    if use_rhog:
        os.system(f'{op} {frhog} {outdir_new}/{suffix_new}-CHARGE-DENSITY.restart')
        logging.info(f'[{op}]: {frhog} -> {outdir_new}/{suffix_new}-CHARGE-DENSITY.restart')
    else: # otherwise we use rhor
        nspin = desc['DFTParamSet'].get('nspin', 1)
        nspin_new = dft_param_set.get('nspin', 1)
        frhor = [os.path.join(outdir, f'SPIN{i}_CHG.cube') 
                 for i in range(1, nspin + 1)]
        frhor_new = [os.path.join(outdir_new, f'SPIN{i}_CHG.cube') 
                     for i in range(1, nspin_new + 1)]
        if nspin == nspin_new:
            for f1, f2 in zip(frhor, frhor_new):
                os.system(f'{op} {f1} {f2}')
                logging.info(f'[{op}]: {f1} -> {f2}')
        elif nspin < nspin_new:
            for i in range(1, nspin_new+1):
                os.system(f'cp {frhor[0]} {frhor_new[i - 1]}')
        else:
            errormsg = 'Cannot decrease the number of spins.'
            logging.error(errormsg)
            raise ValueError(errormsg)
        # remove rhog because it is too large
        os.system(f'rm -f {frhog}')
        logging.info(f'Delete auto-generated rhog file: {frhog}')
    return jobdir, True

def driver(abacus, workdir, orbdir, elem, fpsp, celldm, ecutjy, ecutgrid, dryrun = False):
    '''
    the driver function to run the kinetic energy cutoff convergence test.
    '''
    forbs = _find_all_orbs(orbdir)

    cwd = workdir
    logging.info(f'Change working directory to {cwd}')
    os.chdir(cwd)
    logging.info(f'Start the convergence test for {elem} with ecutjy {ecutjy} in Ry')

    jydir = []
    ecutjy = [ecutjy] if isinstance(ecutjy, (int, float)) else ecutjy

    for i, e in enumerate(sorted(ecutjy)):
        forb = forbs.get(e)
        if forb is None:
            logging.error(f'Cannot find the orbital file with ecut {e}Ry.')
            continue
        jobdir, run = None, False
        if i == 0: # the first, start from scratch
            jobdir, run = _init_test(elem, fpsp, forb, e, celldm,
                                     dft_param_set={'out_chg': 1, 'ecutwfc': ecutgrid})
        else: # the rest, use the charge density from the previous job
            jobdir, run = _init_test_with_charge(jydir[-1], forb, e, use_rhog=False, by_copy=True,
                                                 dft_param_update = {'ecutwfc': ecutgrid})
        if not dryrun:
            if jobdir is None:
                logging.error(f'Job {jobdir} is not well-defined! Please check what happened.')
                continue
            if not run:
                logging.info(f'Test {jobdir} is skipped because it is already done.')
            else:
                os.chdir(jobdir)
                os.system(abacus)
                os.chdir(cwd)
                logging.info(f'Job {jobdir} is finished.')
            jydir.append(jobdir)
    
    logging.info(f'All jobs are finished. Change working directory back to {cwd}')
    return jydir

def clean_rho(folder):
    '''
    clean the charge density files in the folder
    '''
    folder = [folder] if isinstance(folder, str) else folder
    for f in folder:
        temp = _read_abacus_input(os.path.join(f, 'INPUT'))
        suffix, nspin = [temp.get(k, 'ABACUS') for k in ['suffix', 'nspin']]
        nspin = int(nspin)
        outdir = os.path.join(f, f'OUT.{suffix}')
        frhog = os.path.join(outdir, f'{suffix}-CHARGE-DENSITY.restart')
        frhor = [os.path.join(outdir, f'SPIN{i}_CHG.cube') for i in range(1, nspin + 1)]
        for f in [frhog] + frhor:
            if os.path.exists(f):
                os.system(f'rm -f {f}')
                logging.info(f'Delete {f}')
    return True

def main(params, dryrun = False, clean = True):
    '''
    the main workflow of the kinetic energy cutoff convergence of jy basis test
    '''
    fpsp = os.path.abspath(params['fpsp'])
    elem = params['elem']

    celldm = params['celldm']
    cwd = params.get('cwd', os.getcwd())

    options = {'workdir': cwd,
               'abacus': params['abacus_command'],
               'orbdir': os.path.abspath(params['orbital_dir']),
               'elem': elem,
               'fpsp': fpsp,
               'celldm': celldm,
               'ecutjy': params['ecutjy'],
               'ecutgrid': params['ecutwfc'],
               'dryrun': dryrun}
    
    clean_these = driver(**options)
    if clean:
        clean_rho(clean_these)
    
    return cwd, elem, params['ecutjy'], params['ecutwfc']

def init():
    '''
    initialize the workflow by read-in the command line
    '''
    parser = argparse.ArgumentParser(description = 'Initialize the lmax convergence test')
    parser.add_argument('-i', '--input', default = None, type = str, help = 'the json input file')
    args = parser.parse_args()

    if args.input is None:
        return None
    
    with open(args.input) as f:
        config = json.load(f)

    elem, fpsp, celldm = config['elem'], config['fpsp'], config['celldm']
    if not os.path.exists(fpsp):
        raise FileNotFoundError(f'Cannot find the pseudopotential file {fpsp}')

    orbital_dir = config['orbital_dir']
    if not os.path.exists(orbital_dir):
        raise FileNotFoundError(f'The orbital directory {orbital_dir} does not exist.')
    ecutwfc = _convert_to_int_if_possible(float(config['ecutwfc']))
    ecutjy = config['ecutjy']
    ecutjy = [ecutjy] if isinstance(ecutjy, (int, float)) else ecutjy
    ecutjy = [_convert_to_int_if_possible(float(e)) for e in ecutjy]

    return dict([('abacus_command', config['abacus_command']),
                 ('elem', elem), ('fpsp', fpsp), ('celldm', celldm), 
                 ('orbital_dir', orbital_dir), ('ecutjy', ecutjy), ('ecutwfc', ecutwfc)])

if __name__ == '__main__':

    default = {
        'abacus_command': 'OMP_NUM_THREADS=1 mpirun -np 16 abacus',
        'elem': 'H',
        'fpsp': os.path.abspath('PP_ORB_DriverTest/H_ONCV_PBE-1.0.upf'),
        'celldm': 20.0,
        'orbital_dir': os.path.abspath('PP_ORB_DriverTest'),
        'ecutjy': [10, 20, 40, 60, 80, 100, 150, 200],
        'ecutwfc': 150
    }

    params = init()
    if params is None:
        print('WARNING: no input file is specified, will use default parameter proceed the following run')
    params = default if params is None else params

    # starts logging
    flog = f'{time.strftime("%Y%m%d%H%M%S")}.log'
    logging.basicConfig(filename = flog, 
                        level = logging.INFO, 
                        format = '%(asctime)s - %(message)s')
    logging.info(f'Starts the EkinConvergenceTestDriver with parameters: {params}')
    temp = dict(zip(('cwd', 'elem', 'ecutjy', 'ecutwfc'), main(params,
                                                               dryrun=False, clean=True)))
    logging.info(f'The main workflow is finished. The results are: {temp}')
    logging.shutdown()
    