'''
Introduction
------------
this driver performs lmax-rcut joint convergence test on one defined dimer
structure (characterized by bond length) with ABACUS.

Run
---
Prepare a json file containing the following keys:
lmin : int
    the minimum l value to start with
lmax : int
    the maximum l value to end with. Test will be performed for each l value in
    range [lmin, lmax]
dl : int
    the step size for l
rmin : float
    the minimum rcut value to start with
rmax : float
    the maximum rcut value to end with. Test will be performed for each rcut value in
    range [rmin, rmax]
dr : float
    the step size for rcut
elem : str
    the element symbol
bl : float
    the bond length of the molecule, given in angstrom
fpsp : str
    the pseudopotential file name
celldm : float
    the dimension of the cell, given in bohr
orbital_dir : str
    the directory containing the orbitals
ecutwfc : float
    the parameter controls the grid integration, given in Rydberg. This value must be
    larger than the value that can ensure the convergence of pseudopotential. For more
    pseudopotential convergence test information, see ABACUS-Pseudopot-Nao Square:
    https://kirk0830.github.io/ABACUS-Pseudopot-Nao-Square/pseudopotential/pseudopotential.html

Then run the following command:
```
python3 LmaxConvergenceTestDriver.py -i input.json
```

The driver will perform the lmax-rcut joint convergence test on the defined dimer
structure. The results will be stored in the current working directory.
'''

import os
import re
import json
import uuid

# for logging
import time
import logging

# for unittest
import unittest

# because we can only use command line mode on Bohrium, so we need to use argparse
import argparse

# because not sure if the remote has numpy, so use math instead
from math import sin, cos, sqrt, acos, degrees, radians

def _convert_to_int_if_possible(s, thr = 1e-6):
    '''
    convert a float number to int if possible
    '''
    if abs(s - round(s)) < thr:
        return int(round(s))
    return s

def _parse_orb_comp(orb):
    '''
    parse the orb components information in pattern like '21s20p20d19f19g18h'
    '''
    m = re.match(r'((\d+)([spdfghiklm]))+', orb)
    if not m:
        raise ValueError(f'Invalid orb component: {orb}')
    spectrum = 'spdfghiklm'
    lmax = 0
    for s in spectrum[::-1]:
        if s in orb:
            lmax = spectrum.index(s) + 1
            break
    temp = dict([(m.group(2), int(m.group(1))) for m in re.finditer(r'(\d+)([spdfghiklm])', orb)])
    return [temp.get(spectrum[l], 0) for l in range(lmax)]

def _parse_forb(fn):
    '''
    parse the information of an ABACUS orbital file by its name
    '''
    
    fn = os.path.basename(fn) if '/' in fn else fn
    # abacus orbital files' names in format N_gga_7au_100Ry_21s20p20d19f19g18h.orb
    pat = r'^([A-Z][a-z]?)_gga_(\d+)au_(\d+(\.\d+)?)Ry_(\w+)\.orb$'
    m = re.match(pat, fn)
    if not m:
        raise ValueError(f'Invalid orbital file name: {fn}')
    elem, rcut, ecut, _, orbs = m.groups()
    return dict([('elem', elem), 
                 ('rcut', _convert_to_int_if_possible(float(rcut))), 
                 ('ecut', _convert_to_int_if_possible(float(ecut))), 
                 ('nzeta', _parse_orb_comp(orbs))])

def _find_all_orbs(folder):
    '''
    scan all orbitals in present folder, and store the information in a dictionary 
    '''
    logging.info(f'Start to find all orbitals in {folder}...')
    orbs = {}
    for fn in os.listdir(folder):
        if fn.endswith('.orb'):
            r, lmax = _parse_forb(fn)['rcut'], len(_parse_forb(fn)['nzeta']) - 1
            orbs[(lmax, r)] = os.path.join(folder, fn)
            logging.info(f'Found orbital file {fn} with rcut {r} and lmax {lmax}.')
    logging.info(f'Summary: found {len(orbs)} orbitals in {folder}.')

    return orbs

# our job is described by (bond_length, lmax, rcut), these three parameters can uniquely identify a job

def _write_dft_param_set(outdir, dft_param_set):
    '''
    write the ABACUS INPUT file into the outdir
    '''
    if not os.path.exists(outdir):
        os.makedirs(outdir, exist_ok = True)
    fn = os.path.join(outdir, 'INPUT')
    with open(fn, 'w') as f:
        f.write('# this file is automatically generated by the LmaxConvergenceTestDriver\n')
        f.write('INPUT_PARAMETERS\n')
        for k, v in dft_param_set.items():
            f.write(f'{k:<15} {v}\n')
    return fn

def _read_abacus_input(fn):
    '''
    read the abacus input and return a dict
    '''
    with open(fn) as f:
        lines = [l.strip().split('#')[0] for l in f.readlines() if not l.startswith('#')
                 and not l.startswith('INPUT_PARAMETERS')]
    lines = [l for l in lines if l]
    return dict([(l.split()[0], ' '.join(l.split()[1:])) for l in lines])

def _unit_convert(value, from_unit, to_unit):
    '''convert unit'''
    to_unit, from_unit = map(str.lower, [to_unit, from_unit])
    factor = {'bohr': 1, 'angstrom': 0.52917721067}
    return value * factor[to_unit] / factor[from_unit]

def _build_dimer_in_cell(elem, bl, celldm, unit = 'bohr'):
    '''
    build a dict storing cell information
    '''
    celldm = _unit_convert(celldm, unit, 'angstrom')
    bl = _unit_convert(bl, unit, 'angstrom')
    return {'a': celldm, 'b': celldm, 'c': celldm, 'alpha': 90, 'beta': 90, 'gamma': 90,
            'coords': [[0, 0, 0], [bl, 0, 0]],
            'labels': [elem] * 2, 'kinds': [elem], 'labels_kinds_map': [0, 0]}

def _build_atomspec(elem, fpsp, forb):
    '''
    build a dict storing atom species information
    '''
    return {'symbol': elem, 'pp': fpsp, 'nao': forb}

def _abc_angles_to_vec(a, b, c, alpha, beta, gamma):
    '''
    convert the a, b, c, alpha, beta, gamma to lattice vectors
    '''
    alpha, beta, gamma = [radians(x) for x in (alpha, beta, gamma)]
    na, nb, nc = a, b, c
    a = [na, 0, 0]
    b = [nb * cos(gamma), nb * sin(gamma), 0]
    c1 = nc * cos(beta)
    c2 = (nb * nc * cos(alpha) - b[0] * c1) / b[1]
    c3 = sqrt(nc**2 - c1**2 - c2**2)
    c = [c1, c2, c3]
    return a, b, c

def _vec_to_abc_angles(a, b, c):
    '''
    convert the lattice vectors to a, b, c, alpha, beta, gamma
    '''
    na = sqrt(a[0]**2 + a[1]**2 + a[2]**2)
    nb = sqrt(b[0]**2 + b[1]**2 + b[2]**2)
    nc = sqrt(c[0]**2 + c[1]**2 + c[2]**2)
    alpha = degrees(acos((b[0]*c[0] + b[1]*c[1] + b[2]*c[2]) / (nb * nc)))
    beta = degrees(acos((a[0]*c[0] + a[1]*c[1] + a[2]*c[2]) / (na * nc)))
    gamma = degrees(acos((a[0]*b[0] + a[1]*b[1] + a[2]*b[2]) / (na * nb)))
    return na, nb, nc, alpha, beta, gamma

def _write_abacus_stru(outdir, cell, atom_species):
    '''
    write an ABACUS STRU file into outdir, with the cell dict and atom_species list of dict
    '''
    out =  'ATOMIC_SPECIES\n'
    for a in atom_species:
        out += f'{a["symbol"]} {a.get("mass", 1.000)} {os.path.basename(a["pp"])}\n'
    
    if all([a.get('nao') for a in atom_species]):
        out += '\nNUMERICAL_ORBITAL\n'
        for a in atom_species:
            out += f'{os.path.basename(a["nao"])}\n'

    out += '\nLATTICE_CONSTANT\n1.889726877\n\nLATTICE_VECTORS\n'
    for v in _abc_angles_to_vec(*[cell[k] for k in ['a', 'b', 'c', 'alpha', 'beta', 'gamma']]):
        out += f'{" ".join([f"{x:.10f}" for x in v])}\n'
    
    out += '\nATOMIC_POSITIONS\nCartesian_angstrom_center_xyz\n'
    temp = ''
    for ia, a in enumerate(cell['labels']):
        elem = cell['kinds'][cell['labels_kinds_map'][ia]]
        if temp != elem:
            nat = cell['labels'].count(a)
            out += f'{elem}\n0.00\n{nat}\n'
            temp = elem
        out += f'{" ".join([f"{x:.10f}" for x in cell["coords"][ia]])}\n'
    out += '\n'
    fn = os.path.join(outdir, 'STRU')
    os.makedirs(outdir, exist_ok = True)
    with open(fn, 'w') as f:
        f.write(out)
    return fn

def _write_apns_desc(outdir, dft_param_set, atom_species, cell):
    '''
    write a APNS (ABACUS Pseudopotential Nao Square) job description file (in json)
    '''
    atom_species = [atom_species] if isinstance(atom_species, dict) else atom_species
    symbol = atom_species[0]['symbol']
    desc = {'DFTParamSet': dft_param_set,
            'AtomSpecies': atom_species,
            'Cell': cell,
            'CellGenerator': {'identifier': 'molecule', 'config': f'{symbol}_dimer'}}
    fn = os.path.join(outdir, f'description.json')
    os.makedirs(outdir, exist_ok = True)
    with open(fn, 'w') as f:
        json.dump(desc, f, indent = 4)
    return fn

def _define_outdir(elem, bl, lmax, rcut, use_uuid = False):
    '''
    define the job folder based on the bond length, lmax and rcut
    '''
    if use_uuid:
        return str(uuid.uuid4())
    return f'{elem}_bl{bl:.2f}A_lmax{lmax}_rcut{rcut:.2f}au'

def _skip_test(folder):
    '''
    check if the test is already done
    '''
    if not os.path.exists(folder):
        return False
    temp = _read_abacus_input(os.path.join(folder, 'INPUT'))
    suffix, nspin = [temp.get(k, 'ABACUS') for k in ['suffix', 'nspin']]
    nspin = int(nspin)

    outdir = os.path.join(folder, f'OUT.{suffix}')
    if temp.get('scf_nmax', 100) == '1':
        return os.path.exists(os.path.join(outdir, 'istate.info'))
    
    frhog = os.path.join(outdir, f'{suffix}-CHARGE-DENSITY.restart')
    frhor = [os.path.join(outdir, f'SPIN{i}_CHG.cube') for i in range(1, nspin + 1)]
    return os.path.exists(frhog) or all([os.path.exists(f) for f in frhor])

def _init_test(elem, fpsp, forb, bl, celldm, dft_param_set = None, use_uuid = False):
    '''
    initialize a lmax convergence test job with given parameters

    Returns
    -------
    outdir : str
        the output directory
    run : bool
        if True, the job is not skipped
    '''
    default_param_set = {'nspin': 1, 'calculation': 'scf', 
                         'ecutwfc': 100, 'symmetry': 0,
                         'gamma_only': 1,
                         'basis_type': 'lcao', 'ks_solver': 'scalapack_gvx',
                         'out_chg': -1, 'init_chg': 'auto'}
    dft_param_set = {} if dft_param_set is None else dft_param_set
    dft_param_set = default_param_set | dft_param_set

    cell = _build_dimer_in_cell(elem, bl, celldm, 'angstrom')
    atom_species = _build_atomspec(elem, fpsp, forb)

    orb = _parse_forb(forb) if forb is not None else None
    dft_param_set.update({'pseudo_dir': os.path.dirname(fpsp), 
                          'orbital_dir': os.path.dirname(forb) if forb is not None else None})
    conditional = {'lmax': len(orb['nzeta']) - 1, 
                   'rcut': orb['rcut'],
                   'use_uuid': use_uuid} if orb is not None else {'lmax': 0, 'rcut': 0, 'use_uuid': True}
    outdir = _define_outdir(**(conditional|{'elem': elem, 'bl': bl}))
    if _skip_test(outdir):
        logging.info(f'Test {outdir} is skipped because it is already done.')
        return outdir, False
    _write_abacus_stru(outdir, cell, [atom_species])
    _write_apns_desc(outdir, dft_param_set, atom_species, cell)
    _write_dft_param_set(outdir, dft_param_set)
    return outdir, True

def _init_test_with_charge(folder, forb, use_rhog = False, by_copy = False, dft_param_update = None):
    '''
    once a job is finished, we use the charge density as the initial guess of charge
    to do the next job. The l and rcut parameters will be updated.

    Parameters
    ----------
    folder : str
        the folder containing the previous job
    forb : str
        the new orbital file name
    use_rhog : bool
        if True, use the charge density file stored in Gspace, otherwise use the one
        in realspace. For highly heterogenous system, the realspace one is recommended.
    by_copy : bool
        if True, copy the charge density file, otherwise move it.
    dft_param_update : dict
        the updated DFT parameters
    
    Returns
    -------
    jobdir : str
        the output directory
    run : bool
        if True, the job is not skipped
    '''
    # load the description of the previous job
    desc = os.path.join(folder, 'description.json')
    with open(desc) as f:
        desc = json.load(f)

    # refreshing the dft_param_set
    dft_param_set = desc['DFTParamSet'].copy()
    dft_param_set['init_chg'] = 'file'
    dft_param_set['out_chg'] = 1 if not use_rhog else 0
    dft_param_set.update(dft_param_update or {})
    # we change it to file, so that ABACUS will throw if there is no charge file
    
    atom_species = desc['AtomSpecies'][0]
    elem, fpsp, _ = atom_species['symbol'], atom_species['pp'], atom_species['nao']
    
    cell = desc['Cell']
    bl = abs(cell['coords'][1][0] - cell['coords'][0][0])
    celldm = cell['a']

    suffix = _read_abacus_input(os.path.join(folder, 'INPUT')).get('suffix', 'ABACUS')
    outdir = os.path.join(folder, f'OUT.{suffix}')

    jobdir, run = _init_test(elem, fpsp, forb, bl, celldm, dft_param_set)
    if not run: # skip the job if it is already done
        return jobdir, False
    suffix_new = dft_param_set.get('suffix', 'ABACUS')
    outdir_new = os.path.join(jobdir, f'OUT.{suffix_new}')
    os.makedirs(outdir_new, exist_ok = True)

    frhog = os.path.join(outdir, f'{suffix}-CHARGE-DENSITY.restart')
    op = 'cp' if by_copy else 'mv'
    if use_rhog:
        os.system(f'{op} {frhog} {outdir_new}/{suffix_new}-CHARGE-DENSITY.restart')
        logging.info(f'[{op}]: {frhog} -> {outdir_new}/{suffix_new}-CHARGE-DENSITY.restart')
    else: # otherwise we use rhor
        nspin = desc['DFTParamSet'].get('nspin', 1)
        nspin_new = dft_param_set.get('nspin', 1)
        frhor = [os.path.join(outdir, f'SPIN{i}_CHG.cube') 
                 for i in range(1, nspin + 1)]
        frhor_new = [os.path.join(outdir_new, f'SPIN{i}_CHG.cube') 
                     for i in range(1, nspin_new + 1)]
        if nspin == nspin_new:
            for f1, f2 in zip(frhor, frhor_new):
                os.system(f'{op} {f1} {f2}')
                logging.info(f'[{op}]: {f1} -> {f2}')
        elif nspin < nspin_new:
            for i in range(1, nspin_new+1):
                os.system(f'cp {frhor[0]} {frhor_new[i - 1]}')
        else:
            errormsg = 'Cannot decrease the number of spins.'
            logging.error(errormsg)
            raise ValueError(errormsg)
        # remove rhog because it is too large
        os.system(f'rm -f {frhog}')
        logging.info(f'Delete auto-generated rhog file: {frhog}')
    return jobdir, True

def init():
    '''
    initialize the workflow for lmax convergence test. Use -i flag to specify
    the json input file. In the json file, the following keys are needed:

    Keywords
    --------
    abacus_command : str
        the ABACUS command to run the job

    lmin : int
        the minimum l value to start with
    
    lmax : int
        the maximum l value to end with. Test will be performed for each l value in
        range [lmin, lmax]

    dl : int
        the step size for l

    rmin : float
        the minimum rcut value to start with

    rmax : float
        the maximum rcut value to end with. Test will be performed for each rcut value in
        range [rmin, rmax]

    dr : float
        the step size for rcut

    elem : str
        the element symbol
    
    bl : float
        the bond length of the molecule, given in angstrom

    fpsp : str
        the pseudopotential file name
    
    celldm : float
        the dimension of the cell, given in bohr

    orbital_dir : str
        the directory containing the orbitals

    ecutwfc : float
        the parameter controls the grid integration, given in Rydberg. This value must be
        larger than the value that can ensure the convergence of pseudopotential. For more
        pseudopotential convergence test information, see ABACUS-Pseudopot-Nao Square:
        https://kirk0830.github.io/ABACUS-Pseudopot-Nao-Square/pseudopotential/pseudopotential.html
    '''
    parser = argparse.ArgumentParser(description = 'Initialize the lmax convergence test')
    parser.add_argument('-i', '--input', default = None, type = str, help = 'the json input file')
    args = parser.parse_args()

    if args.input is None:
        return None
    
    with open(args.input) as f:
        config = json.load(f)

    lmin, lmax, dl = int(config['lmin']), int(config['lmax']), int(config.get('dl', 1))
    rmin = _convert_to_int_if_possible(float(config['rmin']))
    rmax = _convert_to_int_if_possible(float(config['rmax']))
    dr = _convert_to_int_if_possible(float(config.get('dr', 1)))

    elem, fpsp, celldm = config['elem'], config['fpsp'], config['celldm']
    if not os.path.exists(fpsp):
        raise FileNotFoundError(f'The pseudopotential file {fpsp} does not exist.')

    bl = float(config['bl'])

    nscf_energy = config.get('nscf_energy', False)

    orbital_dir = config['orbital_dir']
    if not os.path.exists(orbital_dir):
        raise FileNotFoundError(f'The orbital directory {orbital_dir} does not exist.')
    ecutwfc = _convert_to_int_if_possible(float(config['ecutwfc']))

    return dict([('abacus_command', config['abacus_command']),
                 ('lmin', lmin), ('lmax', lmax), ('dl', dl),
                 ('rmin', rmin), ('rmax', rmax), ('dr', dr),
                 ('elem', elem), ('fpsp', fpsp), ('celldm', celldm), 
                 ('bl', bl),
                 ('nscf_energy', nscf_energy),
                 ('orbital_dir', orbital_dir), ('ecutwfc', ecutwfc)])

def _linspace(start, end, step):
    '''
    a simple implementation of linspace
    '''
    return [start + i * step for i in range(int((end - start) / step) + 1)]

def _jy_scf_thread_driver(abacus, workdir, orbdir, elem, fpsp, all_l, all_r, celldm, bl, ecutgrid, dryrun = False,
                          restart_from_r = True):
    '''
    the workflow of one bond length. The strategy is,

    1. perform an scf calculation with the minimal rcut and minimal lmax. Set the out_chg
       to 1, so that the charge density will be outputed.
    2. start a new job (with higher rcut but the same lmax) with the charge density file
       dumped from the previous job, iteratively repeat this step until the rcut reaches
       rmax.
    3. increase the lmax by 1, with the charge density file dumped from step 1.
    4. repeat step 2 until the lmax reaches lmax.
    '''
    forbs = _find_all_orbs(orbdir)

    cwd = workdir
    logging.info(f'Change working directory to {cwd}')
    os.chdir(cwd)
    logging.info(f'Starts the lmax convergence test for {elem} with bond length {bl:.2f}A')

    jydir = []
    rmin, lmin = all_r[0], all_l[0]
    for i, l in enumerate(all_l):
        for j, r in enumerate(all_r):
            logging.info(f'Starts the job with lmax {l} and rcut {r:.2f}au')
            jobdir, run = None, False
            if (l, r) == (lmin, rmin): # the first job
                jobdir, run = _init_test(elem, fpsp, forbs[(l, r)], bl, celldm,
                                         dft_param_set={'out_chg': 1, 'ecutwfc': ecutgrid})
            else:
                if not restart_from_r:
                    if l != lmin: # not the first lmax, restart charge from the last lmax
                        source = os.path.join(cwd, _define_outdir(elem, bl, all_l[i - 1], r))
                    else: # the case of i == 0 and j != 0, retain all the charge.
                        source = os.path.join(cwd, _define_outdir(elem, bl, l, all_r[j - 1]))
                else: # restart_from_r:
                    if r != rmin:
                        source = os.path.join(cwd, _define_outdir(elem, bl, l, all_r[j - 1]))
                    else: # the case of the first rcut but not the first lmax
                        source = os.path.join(cwd, _define_outdir(elem, bl, all_l[i - 1], r))
                jobdir, run = _init_test_with_charge(source, forbs[(l, r)], 
                                                     use_rhog = False, by_copy = True)
            if not dryrun:
                if jobdir is None:
                    logging.error(f'Job {jobdir} is not well-defined! Please check what happened.')
                    continue
                if not run:
                    logging.info(f'Test {jobdir} is skipped because it is already done.')
                else:
                    os.chdir(jobdir)
                    os.system(abacus)
                    os.chdir(cwd)
                    logging.info(f'Job {jobdir} is finished.')
                jydir.append(jobdir)

    logging.info(f'The lmax convergence test for {elem} with bond length {bl:.2f}A is finished.')
    return jydir

def _jy_nscf_driver(abacus, workdir, restart_with, orbdir, elem, fpsp, all_l, all_r, celldm, bl, ecutgrid, dryrun = False):
    '''the nscf run always starts with the charge density atomic guess, so different
    jy-basis calculations are independent
    '''
    forbs = _find_all_orbs(orbdir)

    cwd = workdir
    logging.info(f'Change working directory to {cwd}')
    os.chdir(cwd)
    logging.info(f'Starts the lmax convergence test for {elem} with bond length {bl:.2f}A')

    lcao_dft_param = {'scf_nmax': 1, 'basis_type': 'lcao', 'ks_solver': 'scalapack_gvx', 
                      'ecutwfc': ecutgrid, 'out_chg': -1}

    jydir = []
    #rmin, lmin = all_r[0], all_l[0]
    for _, l in enumerate(all_l):
        for _, r in enumerate(all_r):
            logging.info(f'Starts the job with lmax {l} and rcut {r:.2f}au, charge density starts from {restart_with}')
            jobdir, run = _init_test_with_charge(restart_with, forbs[(l, r)], 
                                                 use_rhog = False, by_copy = True,
                                                 dft_param_update = lcao_dft_param)
            if not dryrun:
                if jobdir is None:
                    logging.error(f'Job {jobdir} is not well-defined! Please check what happened.')
                    continue
                if not run:
                    logging.info(f'Test {jobdir} is skipped because it is already done.')
                else:
                    os.chdir(jobdir)
                    os.system(abacus)
                    os.chdir(cwd)
                    logging.info(f'Job {jobdir} is finished.')
                jydir.append(jobdir)
    
    logging.info(f'The lmax convergence test for {elem} with bond length {bl:.2f}A is finished.')
    return jydir

def _pw_scf_driver(abacus, workdir, restart_with, elem, fpsp, celldm, bl, ecutwfc, dryrun = False):
    '''
    perform a pw run, will yield the reference data to compare with jy
    '''
    logging.info(f'Starts the pw run for {elem} with bond length {bl:.2f}A, charge density starts from {restart_with}')
    jobdir, run = _init_test_with_charge(restart_with, None, False, True, 
                                         {'basis_type': 'pw', 'ks_solver': 'dav', 'ecutwfc': ecutwfc})
    if not dryrun:
        if jobdir is None:
            logging.error(f'Job {jobdir} is not well-defined! Please check what happened.')
            return jobdir
        if not run:
            logging.info(f'Test {jobdir} is skipped because it is already done.')
        else:
            os.chdir(jobdir)
            os.system(abacus)
            os.chdir(workdir)
            logging.info(f'Job {jobdir} is finished.')
    return jobdir

def _pw_nscf_driver(abacus, workdir, elem, fpsp, celldm, bl, ecutwfc, dryrun = False):
    '''
    perform a pw run, will yield the reference data to compare with jy
    '''
    jobdir, run = _init_test(
        elem, fpsp, None, bl, celldm,
        dft_param_set={'out_chg': 1, 
                       'ecutwfc': ecutwfc,
                       'scf_nmax': 1000, # dangerous, but we need to ensure the convergence
                       'smearing_method': 'gauss',
                       'smearing_sigma': 0.015, # the recommended, in Ry
                       'mixing_type': 'broyden',
                       'mixing_beta': 0.25, # ensuring the convergence, 0.8 is the default value
                       'mixing_ndim': 12,
                    #    'scf_thr': 1e-2, # a relatively large value, means SCF convergence not relies on it
                    #    'scf_ene_thr': 1e-8, # in eV, 1 mkcal/mol/atom = 2.15e-05 eV
                       'basis_type': 'pw', 
                       'ks_solver': 'dav'})
    if not dryrun:
        if jobdir is None:
            logging.error(f'Job {jobdir} is not well-defined! Please check what happened.')
            return jobdir
        if not run:
            logging.info(f'Test {jobdir} is skipped because it is already done.')
        else:
            os.chdir(jobdir)
            os.system(abacus)
            os.chdir(workdir)
            logging.info(f'Job {jobdir} is finished.')
    return jobdir

def clean_rho(folder):
    '''
    clean the charge density files in the folder
    '''
    folder = [folder] if isinstance(folder, str) else folder
    for f in folder:
        temp = _read_abacus_input(os.path.join(f, 'INPUT'))
        suffix, nspin = [temp.get(k, 'ABACUS') for k in ['suffix', 'nspin']]
        nspin = int(nspin)
        outdir = os.path.join(f, f'OUT.{suffix}')
        frhog = os.path.join(outdir, f'{suffix}-CHARGE-DENSITY.restart')
        frhor = [os.path.join(outdir, f'SPIN{i}_CHG.cube') for i in range(1, nspin + 1)]
        for f in [frhog] + frhor:
            if os.path.exists(f):
                os.system(f'rm -f {f}')
                logging.info(f'Delete {f}')

def scf(workdir, abacus, orbdir, elem, fpsp, celldm, bl, l, r, ecutgrid, dryrun = False,
        with_pw = False):
    '''the calculation can either be executed by an SCF or a NSCF way. 
    This is the driver for the SCF calculation.
    '''
    # first run a series of jy jobs
    jydir = _jy_scf_thread_driver(abacus, 
                             workdir, 
                             os.path.abspath(orbdir),
                             elem,
                             fpsp,
                             l,
                             r,
                             celldm,
                             bl,
                             ecutgrid,
                             dryrun)
    # then run a pw job as reference
    pwdir = _pw_scf_driver(abacus,
                      workdir,
                      jydir[-1],
                      elem,
                      fpsp,
                      celldm,
                      bl,
                      ecutgrid,
                      dryrun) if with_pw else None
    
    return jydir + [pwdir] if with_pw else jydir

def nscf(workdir, abacus, orbdir, elem, fpsp, celldm, bl, l, r, ecutgrid, dryrun = False,
         with_pw = False):
    '''the calculation can either be executed by an SCF or a NSCF way. 
    This is the driver for the NSCF calculation.

    2024/12/03
    A pioneering experiment shows the direct NSCF starting from atomic charge superposition
    cannot yield reasonable estimation. So the workflow changed to starting from the charge
    density converged by a PW calculation, then used to restart various jy-basis 
    calculations.
    '''
    logging.info('Estimate the basis completeness by NSCF calculation starting from a PW charge density.')
    # first run a PW job
    pwdir = _pw_nscf_driver(abacus,
                            workdir,
                            elem,
                            fpsp,
                            celldm,
                            bl,
                            ecutgrid,
                            dryrun)
    # then run a series of jy jobs
    jydir = _jy_nscf_driver(abacus,
                            workdir,
                            pwdir,
                            os.path.abspath(orbdir),
                            elem,
                            fpsp,
                            l,
                            r,
                            celldm,
                            bl,
                            ecutgrid,
                            dryrun)
    return [pwdir] + jydir

def main(params, bl, with_pw = False, run_nscf = False, dryrun = False, clean = True):
    '''
    the main workflow of the lmax convergence test
    '''
    fpsp = os.path.abspath(params['fpsp'])
    elem = params['elem']

    lmin, lmax, dl = params['lmin'], params['lmax'], params['dl']
    rmin, rmax, dr = params['rmin'], params['rmax'], params['dr']
    l, r = _linspace(lmin, lmax, dl), _linspace(rmin, rmax, dr)
    l, r = map(lambda x: [_convert_to_int_if_possible(i) for i in x], [l, r])

    celldm = params['celldm']
    if celldm <= _unit_convert(r[-1], 'bohr', 'angstrom')*2 + bl:
        errormsg = f'The cell dimension {celldm} is too small for the molecule with bond length {bl}.'
        logging.error(errormsg)
        raise ValueError(errormsg)

    cwd = params.get('cwd', os.getcwd())

    abacus_driver = nscf if run_nscf else scf
    options = {'workdir': cwd,
               'abacus': params['abacus_command'],
               'orbdir': params['orbital_dir'],
               'elem': elem,
               'fpsp': fpsp,
               'celldm': celldm,
               'bl': bl,
               'l': l,
               'r': r,
               'ecutgrid': params['ecutwfc'],
               'dryrun': dryrun,
               'with_pw': with_pw}
    
    clean_these = abacus_driver(**options)

    if clean:
        clean_rho(clean_these)
        
    return cwd, elem, fpsp, l, r 

class TestLmaxConvergenceTestDriver(unittest.TestCase):
    def test_parse_orb_comp(self):
        logging.info('Testing _parse_orb_comp...')
        self.assertEqual(_parse_orb_comp('21s20p20d19f19g18h'), [21, 20, 20, 19, 19, 18])
        self.assertEqual(_parse_orb_comp('21s20p20d19f19g'), [21, 20, 20, 19, 19])
        self.assertEqual(_parse_orb_comp('21s20p20d19f'), [21, 20, 20, 19])
        self.assertEqual(_parse_orb_comp('21s20p20f'), [21, 20, 0, 20])
        logging.info('Test passed.')

    def test_parse_forb(self):
        logging.info('Testing _parse_forb...')
        self.assertEqual(_parse_forb('H_gga_7au_100Ry_21s20p20d19f19g18h.orb'), 
                         {'elem': 'H', 'rcut': 7.0, 'ecut': 100.0, 'nzeta': [21, 20, 20, 19, 19, 18]})
        self.assertEqual(_parse_forb('Li_gga_7au_100Ry_21s20p20d19f19g.orb'), 
                         {'elem': 'Li', 'rcut': 7.0, 'ecut': 100.0, 'nzeta': [21, 20, 20, 19, 19]})
        self.assertEqual(_parse_forb('O_gga_7au_100Ry_21s20p20f.orb'), 
                         {'elem': 'O', 'rcut': 7.0, 'ecut': 100.0, 'nzeta': [21, 20, 0, 20]})
        self.assertEqual(_parse_forb('H_gga_11au_100Ry_21s20p20d19f19g18h.orb'),
                         {'elem': 'H', 'rcut': 11, 'ecut': 100, 'nzeta': [21, 20, 20, 19, 19, 18]})
        logging.info('Test passed.')

    def test_abacus_input_io(self):
        logging.info('Testing _write_dft_param_set and _read_abacus_input...')
        dft_param_set = {'nspin': 2, 'calculation': 'nscf', 'ecutwfc': 200}
        fn = _write_dft_param_set('LmaxConvergenceTestDriverUnittest', dft_param_set)
        self.assertEqual(_read_abacus_input(fn), {k: str(v) for k, v in dft_param_set.items()})
        os.system(f'rm -rf {fn}')
        logging.info('Test passed.')
    
    def test_abc_angles_and_vec(self):
        logging.info('Testing _abc_angles_to_vec and _vec_to_abc_angles...')
        a, b, c = _abc_angles_to_vec(1, 1, 1, 90, 90, 90)
        for i, e in enumerate([1, 0, 0]):
            self.assertAlmostEqual(a[i], e, delta=1e-6)
        for i, e in enumerate([0, 1, 0]):
            self.assertAlmostEqual(b[i], e, delta=1e-6)
        for i, e in enumerate([0, 0, 1]):
            self.assertAlmostEqual(c[i], e, delta=1e-6)
        na, nb, nc, alpha, beta, gamma = _vec_to_abc_angles(a, b, c)
        self.assertAlmostEqual(na, 1, delta=1e-6)
        self.assertAlmostEqual(nb, 1, delta=1e-6)
        self.assertAlmostEqual(nc, 1, delta=1e-6)
        self.assertAlmostEqual(alpha, 90, delta=1e-6)
        self.assertAlmostEqual(beta, 90, delta=1e-6)
        self.assertAlmostEqual(gamma, 90, delta=1e-6)
        logging.info('Test passed.')

    def test_unit_convert(self):
        logging.info('Testing _unit_convert...')
        self.assertAlmostEqual(_unit_convert(1, 'angstrom', 'bohr'), 1.889726877, delta=1e-6)
        self.assertAlmostEqual(_unit_convert(1.889726877, 'bohr', 'angstrom'), 1, delta=1e-6)
        logging.info('Test passed.')

    def test_init_test(self):
        logging.info('Testing _init_test...')
        dft_param_set = {'nspin': 2, 'calculation': 'nscf',
                         'ecutwfc': 200, 'symmetry': 0, 'gamma_only': 1,
                         'basis_type': 'lcao', 'ks_solver': 'scalapack_gvx'}
        jobdir, _ = _init_test('H', 
                               'H_ONCV_PBE-1.0.upf',
                               'H_gga_7au_100Ry_21s20p20d19f19g18h.orb', 0.6, 7, dft_param_set)
        self.assertTrue(os.path.exists(jobdir))
        os.system(f'rm -rf {jobdir}')
        logging.info('Test passed.')

    @unittest.skip('skip this test because it is quite complex')
    def test_init_test_with_charge(self):
        logging.info('Testing _init_test_with_charge...')
        jobdir, _ = _init_test_with_charge('LmaxConvergenceTestDriverUnittest/H_0.60A_0l_7.00au', 
                                           'H_gga_7au_100Ry_21s20p20d19f19g18h.orb')
        self.assertTrue(os.path.exists(jobdir))
        os.system(f'rm -rf {jobdir}')
        logging.info('Test passed.')
    
    def test_define_outdir(self):
        logging.info('Testing _define_outdir...')
        self.assertEqual(_define_outdir('H', 0.6, 0, 7), 'H_bl0.60A_lmax0_rcut7.00au')
        self.assertEqual(_define_outdir('H', 0.6, 1, 7), 'H_bl0.60A_lmax1_rcut7.00au')
        logging.info('Test passed.')
    
    def test_linspace(self):
        logging.info('Testing _linspace...')
        self.assertEqual(_linspace(1, 5, 1), [1, 2, 3, 4, 5])
        self.assertEqual(_linspace(1, 5, 2), [1, 3, 5])
        self.assertEqual(_linspace(0.1, 0.5, 0.3), [0.1, 0.4])
        logging.info('Test passed.')

    def test_init(self):
        logging.info('Testing init...')
        config = {
            'abacus_command': 'OMP_NUM_THREADS=1 mpirun -np 16 abacus',
            'lmin': 1,
            'lmax': 3,
            'dl': 1,
            'rmin': 6,
            'rmax': 12,
            'elem': 'H',
            'bl': 0.6,
            'fpsp': 'PP_ORB/H_ONCV_PBE-1.0.upf',
            'celldm': 20.0,
            'orbital_dir': 'PP_ORB',
            'ecutwfc': 150
        }
        self.assertEqual(init(), None)
        logging.info('Test passed.')

if __name__ == '__main__':
    # either configure the workflow here or use the command line with an external file
    config = {
        'abacus_command': 'OMP_NUM_THREADS=1 mpirun -np 8 abacus',
        'lmin': 1,
        'lmax': 2,
        'dl': 1,
        'rmin': 6,
        'rmax': 9,
        'dr': 1,
        'elem': 'H',
        'bl': 0.6,
        'fpsp': os.path.abspath('PP_ORB_DriverTest/H_ONCV_PBE-1.0.upf'),
        'celldm': 20.0,
        'orbital_dir': os.path.abspath('PP_ORB_DriverTest'),
        'ecutwfc': 150,
        'nscf_energy': True
    }

    params = init()
    if params is None:
        print('WARNING: no input file is specified, will use default parameter proceed the following run')
    params = config if params is None else params

    # starts logging
    flog = f'{time.strftime("%Y%m%d%H%M%S")}.log'
    logging.basicConfig(filename = flog, 
                        level = logging.INFO, 
                        format = '%(asctime)s - %(message)s')
    logging.info('Starts the LmaxConvergenceTestDriver unittest...')
    run_nscf = params.get('nscf_energy', False)
    logging.info(f'Evaluate the basis set completeness by nscf energy: {run_nscf}')
    # unittest.main(exit=False) # disabled because it will overwrite the argparse (why?)

    # starts the main workflow and perform sanity check on bl
    bl = params.get('bl')
    if bl is None:
        err = 'The bond length is not specified, please check the input file.'
        logging.error(err)
        raise ValueError(err)
    
    logging.info(f'Starts the LmaxConvergenceTestDriver with parameters: {params}')
    temp = dict(zip(('cwd', 'elem', 'fpsp', 'l', 'r' ), main(params,
                                                             bl, 
                                                             with_pw = True, 
                                                             run_nscf = run_nscf, 
                                                             dryrun = False)))
    logging.info(f'The main workflow is finished. The results are: {temp}')
    logging.info('The LmaxConvergenceTestDriver is finished.')
    logging.shutdown() # close the logging file
